[theme]
# Primary accent color for interactive elements.
primaryColor = "#2E7D32"

# Background color for the main content area.
backgroundColor = "#F5F5F5"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#BDBDBD"

# Color used for almost all text.
textColor = "#212121"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"